Repository caicloud/golang-template-project, pull requests merged in 2019-09, with the labels that each got.

#1 feat(*): read available cpus for compiling
  Makefile
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#2 feat(*): remove pre commit
  .pre-commit-config.yaml
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#4 chore(*): add annotation for cpu available
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#3 feat(*): fix todo
  README.md
  pkg/apis/v1/README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#5 chores(Makefile): polish makefile
  .golangci.yml
  Makefile
  build/admin/Dockerfile
  build/controller/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#6 fix(*): Use go env GOPATH for install golangci-lint
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#8 chore(Makefile): mv for loop inside docker
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#9 Refact: polish dockerfiles
  build/admin/Dockerfile
  build/controller/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
