Repository caicloud/golang-template-project, pull requests merged in 2020-05, with the labels that each got.

#16 chore(hack): support setting max cpus manually
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#21 feat(*): add interactive for docker run
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#20 feat(*): use go-common and move version to vendor
  Makefile
  cmd/admin/admin.go
  pkg/version/version.go
  vendor/github.com/caicloud/go-common/version/base.go
  vendor/github.com/caicloud/go-common/version/version.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
